mobil/urls.py
from django.urls import path
from . import views

app_name = 'mobil'

urlpatterns = [
    path('', views.list_mobil, name='list_mobil'),
    path('getAllCarData/', views.getAllCarData, name='getAllCarData'),
    path('tambah/', views.tambah_mobil, name='tambah_mobil'),
    path('detail/<int:index>/', views.detail_mobil, name='detail_mobil'),
    path('add-fav/', views.add_fav, name='add_fav'),
]

sewaAlex/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('users.urls')),
    path('transaksi/', include('transaksi.urls')),
    path('admin/', admin.site.urls),
    path('artikel/', include('artikel.urls')),
    path('mobil/', include('mobil.urls')),
    path('ulasan/', include('ulasan.urls')),
    path('', include('social_django.urls', namespace='social')),
]

transaksi/urls.py
from django.urls import path
from . import views

app_name = "transaksi"

urlpatterns = [
    path('sewa/<int:id>/', views.show, name='show'),
    path('terimakasih/', views.thanksGreeting, name='terimakasih'),
    path('riwayat/', views.riwayat, name='riwayat'),
    path('riwayat/detail/<int:id>/', views.riwayatDetail, name='riwayatDetail')
]

ulasan/urls.py
from django.urls import path
from . import views

app_name = 'ulasan'

urlpatterns = [
    path('<int:index>/', views.daftar_ulasan, name='daftar_ulasan'),
    path('tulis_ulasan/<int:index>/', views.tulis_ulasan, name='tulis_ulasan')
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile_page, name='profile'),
    path('signup/', views.signup_page, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_acc, name='logout'),
    path('edit_profile/', views.edit_profile, name='edit_profile')
]

transaksi/models.py
from django.db import models
from mobil.models import Car

# Create your models here.
class Transaksi(models.Model):
    namaPembeli = models.CharField(max_length=50)
    noHp = models.CharField(max_length=13)
    dari = models.DateTimeField(auto_now=False, auto_now_add=False)
    hingga = models.DateTimeField(auto_now=False, auto_now_add=False)
    mobil = models.ForeignKey(Car, on_delete=models.CASCADE, blank=True)

transaksi/forms.py
from django import forms
from .models import Transaksi

class TransaksiForm(forms.ModelForm):
    class Meta:
        model = Transaksi
        fields = ('namaPembeli', 'noHp', 'dari', 'hingga', 'mobil')

transaksi/views.py
from django.shortcuts import render, redirect
from .models import Transaksi
from .forms import TransaksiForm
from mobil.models import Car
from ulasan.models import Review
from datetime import datetime,date
import math

App_Name = "transaksi"

# Create your views here.
def show(request, id=0):
    mobil = Car.objects.get(id=id)
    if request.method == 'POST':
        url = request.POST
        mobil.sewa = False
        data = {
            'namaPembeli' : url['namaPembeli'],
            'noHp' : url['noHp'],
            'dari' : url['dari'],
            'hingga' : url['hingga'],
            'mobil' : mobil
            }
        form = TransaksiForm(data=data)
        if form.is_valid():
            dari = datetime.strptime(url["dari"] + " 00:00", '%m/%d/%Y %H:%M').timestamp()
            hingga = datetime.strptime(url["hingga"] + " 00:00", '%m/%d/%Y %H:%M').timestamp()
            todayDate = date.today()
            today = datetime.combine(todayDate, datetime.min.time()).timestamp()
            dateValidation = dari < today or hingga < today or hingga < dari
            if dateValidation:
                errorDate = "Waktu yang anda masukkan salah, coba masukkan lagi."
                return render(request, "transaksi/transaksi.html", {"errorDate" : errorDate, 'mobil' : mobil})
            else:
                form.save()
                mobil.save()
                return redirect('transaksi:terimakasih')
    return render(request, "transaksi/transaksi.html", {'mobil' : mobil})

def thanksGreeting(request):
    return render(request, "transaksi/terimakasih.html")

def riwayat(request):
    allTransaksi = Transaksi.objects.all()
    today = datetime.combine(date.today(), datetime.min.time()).timestamp()
    for item in allTransaksi:
        tanggalPengembalian = item.hingga.timestamp()
        if tanggalPengembalian < today:
            mobilId = item.mobil.id
            mobil = Car.objects.get(id=mobilId)
            mobil.sewa = True
            item.delete()
            mobil.save()
    allTransaksi = Transaksi.objects.all()
    return render(request, "transaksi/riwayat.html", {'transaksi' : allTransaksi})

def riwayatDetail(request, id=0):
    mobil = Car.objects.get(id=id)
    list_ulasan = Review.objects.filter(pk=id)
    rating = 5
    counter = 1
    for i in list_ulasan:
        rating += i.rating
        counter += 1
    rating = math.ceil(rating/counter)

    transaksi = Transaksi.objects.get(mobil=mobil)
    hingga = transaksi.hingga
        
    return render(request, "transaksi/detail.html", {'car' : mobil, 'rating': rating, 'hingga':hingga})

templates/transaksi/detail.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
	<link rel="stylesheet" href="{% static 'css/mobil/style_detail.css' %}">
{% endblock css%}

{% block title %} Mobil {{ car.mobil }} {% endblock %}

{% block content %}
<div class="content">
	<section class="row w-100 d-flex justify-content-center">
		<div class="col-sm-6 d-flex flex-column justify-content-center align-items-center">
			<div class="d-flex flex-column align-items-center mobilImg">
				<img src="{% static 'img/mobil/car-black_3.png' %}" class="card-img-top" alt="">
			</div>

			<div class="status">
				<span class="font-weight-bold">STATUS : </span> Sedang disewa hingga <span class="font-weight-bold"> {{hingga}} </span>
			</div>
		</div>

		<div class="tabelDiv p-2">
			<span class="mobil"> Mobil {{ car.mobil }} </span>
			<span class="rating"> Rating : {{ car.rating }}/5 </span>
			<span class="harga"> Harga : {{ car.harga }} </span>
			
			<table class="table-borderless">
				<colgroup>
	      	<col span="1" style="width: 40%;">
	       	<col span="1" style="width: 60%;">
		    </colgroup>

			  <tr>
					<th class="font-weight-bold"> Nama Pemilik </th>
					<td>: {{ car.pemilik }} </td>
			  </tr>

			  <tr>
					<th class="font-weight-bold"> Tahun Keluaran </th>
					<td>: {{ car.tahun }} </td>
			  </tr>

			  <tr>
					<th class="font-weight-bold"> Kota </th>
					<td>: {{ car.kota }} </td>
			  </tr>

			  <tr>
					<th class="font-weight-bold"> Deskripsi</th>
					<td> : </td>
			  </tr>

			  <tr>
					<td colspan="2" class="text">{{ car.deskripsi }} </td>
			  </tr>

			  <tr>
			  	<td class="pt-4">
						<a href="{% url 'ulasan:tulis_ulasan' car.id %}" class="btn yellow">Tambah Ulasan</a>
			  	</td>
			  </tr>
			</table>
	</section>
</div>
{% endblock %}

{% block js %}
	<script src="https://code.iconify.design/1/1.0.4/iconify.min.js"></script>
{% endblock js %}

templates/transaksi/riwayat.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/list.css' %}">
{% endblock css %}

{% block title %}Riwayat{% endblock title %}

{% block content %}
<div class="content">
    <span class="header">Riwayat</span>
    <div class="bodyContent d-flex justify-content-around">
        {% for item in transaksi %}
        <div class="card m-3 p-3 shadow" style="width: 450px; cursor:pointer" onclick="location.href='{% url 'transaksi:riwayatDetail' item.mobil.id %}'">
            <img src="{% static 'img/mobil/car-black_3.png' %}" class="card-img-top" alt="">
            <div class="card-body">
                <h5 class="card-title">{{item.mobil.mobil}}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{item.mobil.pemilik}}</h6>
                <p class="card-text">{{item.mobil.deskripsiSnippet}}</p>
            </div>
        </div>
        {% empty %}
        <div class="content-empty">
            <h1 class="message">Yaah.. Content Masih Kosong</h1>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/transaksi/terimakasih.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
<meta http-equiv="refresh" content="3; url={% url 'transaksi:riwayat' %}">
<link rel="stylesheet" href="{% static 'css/transaksi.css' %}">
{% endblock css %}

{% block title %}Terima Kasih{% endblock title %}

{% block content %}
    <div class="xlSize flex-center-center">
        <h1>Terimakasih Sudah Rental di Kami</h1>
        <span>Pengambilan mobil bisa di lakukan mulai pukul 10:00 pagi waktu pemesanan di kantor kami</span>
        <span>Pengembalian mobil paling telat adalah pukul 10:00 malam waktu pemesanan ke kantor kami</span>
        <span>Keterlambatan pengembalian mobil dikenakan biaya tambahan</span>
    </div>
{% endblock content %}

templates/transaksi/transaksi.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/transaksi.css' %}">
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css">
{% endblock css %}

{% block title %}Transaksi{% endblock title %}

{% block content %}
    <div class="content">
      {% if user.is_authenticated %}
        <div class="mobil">
            <div class="d-flex flex-column align-items-center mobilImg">
				<img src="{% static 'img/mobil/car-black_3.png' %}" class="card-img-top" alt="">
			</div>
            <div class="harga">
                <h5>Perjam : <span class='yellowText'>{{mobil.harga}}</span></h5>
            </div>
        </div>
        <div class="formtransaksi">
            <h1>Transaksi</h1>
            <h5>Data Diri Pembeli :</h5>
            <form action="" method="post">
                {% csrf_token %}
                <input type="hidden" name="carId" value="mobil.id">
                <div class="form-group">
                    <label for="namaPembeli" class="col-form-label">Nama</label>
                    <input type="text" class="form-control" id="namaPembeli" name="namaPembeli" required>
                </div>
                <div class="form-group">
                    <label for="noHp" class="col-form-label">No Hp</label>
                    <input class="form-control" name="noHp" type="tel" placeholder="+62-(812)-3456-7890" id="noHp" required>
                </div>
                <div class="form-group">
                    <label for="dari" class="col-form-label">Dari</label>
                    <div class="input-append date2">
                        <input id="dari" class="{% if errorDate %} is-invalid {% endif %}" autocomplete="off" name="dari" required>
                    </div>
                    <span class="text-danger">{{errorDate}}</span>
                    <script>
                        $('#dari').datepicker({
                            uiLibrary: 'bootstrap4'
                        });
                    </script>
                </div>
                <div class="form-group">
                    <label for="hingga" class="col-form-label">Hingga</label>
                    <div class="input-append date2">
                        <input id="hingga" class="{% if errorDate %} is-invalid {% endif %}" autocomplete="off" name="hingga" required>
                    </div>
                <span class="text-danger">{{errorDate}}</span>
                    <script>
                        $('#hingga').datepicker({
                            uiLibrary: 'bootstrap4'
                        });
                    </script>
                </div>
                <button type="submit" class="btn yellow">Pesan</button>
            </form>
        </div>
      {% else %}
      <section class="px-5 justify-content-center">
        <h4 class="m-3"> Login terlebih dahulu sebelum melakukan transaksi! </h4> 
        <h4 class="m-3"><a href="{% url 'users:login' %}" class="btn yellow">Login Sekarang</a></h4>
      </section>
      {% endif %}
    </div>
{% endblock content %}

{% block js %}
<script src="https://code.iconify.design/1/1.0.4/iconify.min.js"></script>
{% endblock %}