mobil/urls.py
from django.urls import path
from . import views

app_name = 'mobil'

urlpatterns = [
    path('', views.list_mobil, name='list_mobil'),
    path('getAllCarData/', views.getAllCarData, name='getAllCarData'),
    path('tambah/', views.tambah_mobil, name='tambah_mobil'),
    path('detail/<int:index>/', views.detail_mobil, name='detail_mobil'),
    path('add-fav/', views.add_fav, name='add_fav'),
]

sewaAlex/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('users.urls')),
    path('transaksi/', include('transaksi.urls')),
    path('admin/', admin.site.urls),
    path('artikel/', include('artikel.urls')),
    path('mobil/', include('mobil.urls')),
    path('ulasan/', include('ulasan.urls')),
    path('', include('social_django.urls', namespace='social')),
]

transaksi/urls.py
from django.urls import path
from . import views

app_name = "transaksi"

urlpatterns = [
    path('sewa/<int:id>/', views.show, name='show'),
    path('terimakasih/', views.thanksGreeting, name='terimakasih'),
    path('riwayat/', views.riwayat, name='riwayat'),
    path('riwayat/detail/<int:id>/', views.riwayatDetail, name='riwayatDetail')
]

ulasan/urls.py
from django.urls import path
from . import views

app_name = 'ulasan'

urlpatterns = [
    path('<int:index>/', views.daftar_ulasan, name='daftar_ulasan'),
    path('tulis_ulasan/<int:index>/', views.tulis_ulasan, name='tulis_ulasan')
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile_page, name='profile'),
    path('signup/', views.signup_page, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_acc, name='logout'),
    path('edit_profile/', views.edit_profile, name='edit_profile')
]

mobil/models.py
from django.db import models

# Create your models here.
class Car(models.Model):
	mobil = models.CharField('Nama Mobil', max_length=120, null=True)
	pemilik = models.CharField('Nama Pemilik', max_length=120, null=True)
	tahun = models.IntegerField('Tahun Keluaran', null=True)
	kota = models.CharField('Kota', max_length=120, null=True)
	harga = models.CharField('Harga Sewa per Hari', max_length=20, null=True, help_text='contoh : Rp100.000')
	deskripsi = models.TextField('Deskripsi', blank=True)
	foto = models.ImageField('Unggah Foto', upload_to='static/img/mobil/', null=True, blank=True)
	sewa = models.BooleanField(default=True)
	rating = models.IntegerField('Rating', default=5)

	def deskripsiSnippet(self):
		return self.deskripsi[:50] + "..."

mobil/forms.py
from django.forms import ModelForm, forms, Textarea
from .models import Car

class CarForm(ModelForm):
	required_css_class = 'required'
	class Meta:
		model = Car
		widgets = {
			'deskripsi': Textarea(attrs={'rows':4, 'cols':19}),
		}
		fields = [
			'mobil',
			'pemilik',
			'tahun',
			'kota',
			'harga',
			'deskripsi',
			'foto'
		]

mobil/views.py
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden, HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.core.serializers import serialize
from ulasan.models import Review
from .models import Car
from .forms import CarForm

# Create your views here.
def list_mobil(request):
	return render(request, 'mobil/car_list.html')

def detail_mobil(request, index):
	car = Car.objects.get(pk=index)
	fav = False
	if request.user.is_authenticated:
		if request.user.profile in car.profile_set.all():
			fav = True

	return render(request, 'mobil/car_detail.html', {'car': car, "fav": fav})

def tambah_mobil(request):
	if request.method == 'POST':
		form = CarForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			return redirect('/mobil/')
	else:
		form = CarForm()
	return render(request, 'mobil/add_car.html', {'form': form})

@csrf_exempt
def add_fav(request):
	if request.method == 'POST':
		car = Car.objects.get(pk=request.POST['id'])
		current = request.user
		
		if current.profile in car.profile_set.all():
			current.profile.favorit.remove(car)
		else:
			current.profile.favorit.add(car)

		current.save()

	return HttpResponseForbidden()

def getAllCarData(request):
	car_list = Car.objects.all()
	car_list = serialize("json", car_list)
	return HttpResponse(car_list, content_type="text/json-comment-filtered")

templates/mobil/add_car.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block css %}
	<link rel="stylesheet" href="{% static 'css/mobil/style_detail.css' %}">
{% endblock css%}
{% block title %} Sewakan Mobilmu {% endblock title%}

{% block content %}
<div class="content">
	<section class="px-5 justify-content-center">
      {% if user.is_authenticated %}
		<h1 class="mx-auto mb-4 font-weight-bold"> 
			SEWAKAN MOBILMU SEKARANG
		</h1>
	
		<form action="" method="post" enctype="multipart/form-data" novalidate>
			{% csrf_token %}
			{{ form|crispy }}
			<input type="submit" value="Sewakan Sekarang" class="btn yellow my-4"></td>
		</form>
      {% else %}
        <h4 class="m-3"> Login terlebih dahulu sebelum menyewakan mobilmu! </h4> 
        <h4 class="m-3"><a href="{% url 'users:login' %}" class="btn yellow">Login Sekarang</a></h4>
      {% endif %}
	</section>
</div>
{% endblock content %}

templates/mobil/car_detail.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
	<link rel="stylesheet" href="{% static 'css/mobil/style_detail.css' %}">
{% endblock css%}

{% block title %} Mobil {{ car.mobil }} - {{ car.pemilik }} {% endblock %}

{% block content %}
<div class="content">
	<section class="row w-100 d-flex justify-content-center">
		<div class="col-sm-6 d-flex flex-column justify-content-center align-items-center">
			<div class="d-flex flex-column align-items-center mobilImg">
				<img src="{% static 'img/mobil/car-black_3.png' %}" class="card-img-top" alt="">
			</div>
			<a href="{% url 'transaksi:show' id=car.id %}" class="font-weight-bold btn yellow mt-5">SEWA SEKARANG</a>
		</div>

		<div class="tabelDiv p-2">
			<span class="mobil"> 
				Mobil {{ car.mobil }} 
				{% if user.is_authenticated %}
					{% if fav %}
						<i id="{{ car.id }}" class="fa fa-heart click-heart red"></i>
					{% else %}
						<i id="{{ car.id }}" class="far fa-heart click-heart black"></i>
					{% endif %}
				{% endif %}
			</span>
			<span class="rating"> Rating : {{ car.rating }}/5 </span>
			<span class="harga"> Harga : {{ car.harga }} </span>
			
			<table class="table-borderless">
				<colgroup>
	      <col span="1" style="width: 40%;">
	      <col span="1" style="width: 60%;">
		    </colgroup>

			  <tr>
					<th class="font-weight-bold"> Nama Pemilik </th>
					<td>: {{ car.pemilik }} </td>
			  </tr>

			  <tr>
					<th class="font-weight-bold"> Tahun Keluaran </th>
					<td>: {{ car.tahun }} </td>
			  </tr>

			  <tr>
					<th class="font-weight-bold"> Kota </th>
					<td>: {{ car.kota }} </td>
			  </tr>

			  <tr>
					<th class="font-weight-bold"> Deskripsi</th>
					<td> : </td>
			  </tr>

			  <tr>
					<td colspan="2" class="text">{{ car.deskripsi }} </td>
			  </tr>

			  <tr>
			  	<td class="pt-4">
						<a href="{% url 'ulasan:daftar_ulasan' car.id %}" class="btn yellow">Lihat Ulasan</a>
			  	</td>
			  </tr>
			</table>
		</div>
	</section>
</div>
{% endblock %}

{% block js %}
	<script src="https://kit.fontawesome.com/aa8d881418.js" crossorigin="anonymous"></script>
	<script src="{% static 'js/detail_mobil.js' %}"></script> 
{% endblock js %}

templates/mobil/car_list.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
	<link rel="stylesheet" href="{% static 'css/list.css' %}">
{% endblock css%}

{% block title %} Sewa Mobil {% endblock %}

{% block content %}
<div class="content p-5">
	<h1 class="mx-auto mb-4 font-weight-bold header"> 
		SEWA MOBIL
	</h1>
	<div class="search-bar">
		<input type="text" id="search-bar" placeholder="Cari mobil berdasarkan nama atau harga" autocomplete="off">
		<div class="name-suggestion-box" id="suggestionBox">
		</div>
		<div class="overlay-background"  style="display:none"></div>
	</div>
    <div class="bodyContent d-flex justify-content-around" id="carList">
    </div>
</div>
{% endblock %}

{% block js %}
	<script src="{% static 'js/mobil.js' %}"></script>
{% endblock js %}