artikel/urls.py
from django.urls import path
from . import views

app_name = 'artikel'

urlpatterns = [
    path('', views.artikel_homepage),
    path('artikel/', views.artikel_homepage, name="artikelPage"),
    path('artikel/details/<int:id>/', views.artikel1),
]

mobil/urls.py
from django.urls import path
from . import views

app_name = 'mobil'

urlpatterns = [
    path('', views.list_mobil, name='list_mobil'),
    path('getAllCarData/', views.getAllCarData, name='getAllCarData'),
    path('tambah/', views.tambah_mobil, name='tambah_mobil'),
    path('detail/<int:index>/', views.detail_mobil, name='detail_mobil'),
    path('add-fav/', views.add_fav, name='add_fav'),
]

sewaAlex/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('users.urls')),
    path('transaksi/', include('transaksi.urls')),
    path('admin/', admin.site.urls),
    path('artikel/', include('artikel.urls')),
    path('mobil/', include('mobil.urls')),
    path('ulasan/', include('ulasan.urls')),
    path('', include('social_django.urls', namespace='social')),
]

transaksi/urls.py
from django.urls import path
from . import views

app_name = "transaksi"

urlpatterns = [
    path('sewa/<int:id>/', views.show, name='show'),
    path('terimakasih/', views.thanksGreeting, name='terimakasih'),
    path('riwayat/', views.riwayat, name='riwayat'),
    path('riwayat/detail/<int:id>/', views.riwayatDetail, name='riwayatDetail')
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile_page, name='profile'),
    path('signup/', views.signup_page, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_acc, name='logout'),
    path('edit_profile/', views.edit_profile, name='edit_profile')
]

templates/home.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/landingpage.css' %}">
{% endblock css %}

{% block title %}Home{% endblock title %}
{% block content %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <script>
            alert("{{ message }}")
        </script>
        {% endfor %}
    </ul>
    {% endif %}
    
    <div class="content">
        <!-- section1 -->
        <div class="containerGreeting">
            <div class="greeting">
                <img src="{% static 'img/LogoRental.png' %}" width="100%" alt="">
                <p>Ini adalah sebuah website yang harusnya menjual mobil. Dibuat oleh Muhammad Hafiz Maulana, Jeremiah Garcia Tennes, Fairuza Raryasdya Ayunda, dan Farah Nazihah. Desainnya sangat sederhana. Layoutnya sangat menggambarkan mahasiswa fasilkom. sedikit berantakan tapi yasudah lah kami sudah berusaha. Selamat berkunjung, semoga anda tidak bingung.</p>
            </div>
        </div>
        <!-- endSection1 -->
    </div>
{% endblock content %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    <link rel="icon" href="{% static 'img/headLogo.png' %}" type="image/gif" sizes="16x16">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- FONT -->
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    {% block css %}

    {% endblock css %}
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <div class="mobileNavCollaps">
        <div class="collapse" id="navbarToggleExternalContent">
            <div class="yellow p-4 d-flex flex-column">
              <span class="py-1"><a href="{% url 'transaksi:riwayat' %}" class="text-white text-decoration-none">Riwayat</a></span>
              <span class="py-1"><a href="{% url 'artikel:artikelPage' %}" class="text-white text-decoration-none">Artikel</a></span>
              <span class="py-1"><a href="{% url 'mobil:list_mobil' %}" class="text-white text-decoration-none">Rental Sekarang</a></span>
              <span class="py-1"><a href="{% url 'mobil:tambah_mobil' %}" class="text-white text-decoration-none">Rentalkan Mobilmu</a></span>
            </div>
        </div>
    </div>
    <div class="navbar {% if home is not none %} white {% else %} blue {% endif %} ">
        <div class="logo"><a href="{% url 'users:index' %}"><img src="{% static 'img/LogoRental.png' %}" height="30px" alt=""></a></div>
        <div class="option">
            <span><a href="{% url 'transaksi:riwayat' %}">Riwayat</a></span>
            <span><a href="{% url 'artikel:artikelPage' %}">Artikel</a></span>
            <div class="btn-group">
                <button id="rental" type="button" class="btn yellow dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Rental
                </button>
                <div class="dropdown-menu">
                  <a id="car_list" class="dropdown-item" href="{% url 'mobil:list_mobil' %}">Rental Sekarang</a>
                  <a class="dropdown-item" href="{% url 'mobil:tambah_mobil' %}">Rentalkan Mobilmu</a>
                </div>
            </div>
            {% if user.is_authenticated %}
            <div class="btn-group mx-2">
                <button id="drop-akun" type="button" class="btn {% if home is not none %} btn-outline-warning {% else %} btn-nav-login {% endif %} dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Akun
                </button>
                <div class="dropdown-menu">
                  <a id="profile" class="dropdown-item" href="{% url 'users:profile' %}">Profile</a>
                  <a id="logout-nav" class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                </div>
            </div>
            {% else %}
            <button id="login" class="btn {% if home is not none %} btn-outline-warning {% else %} btn-nav-login {% endif %} mx-2" onclick="location.href='{% url 'users:login' %}'">Login</button>
            {% endif %}
        </div>
        <div class="mobile-nav">
            <button class="btn yellow dropdown-toggle" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                Rental
            </button>
        </div>
    </div>
    {% block content %}
    
    {% endblock content %}
    <div class="footer">
        <div class="logo"><img src="{% static 'img/LogoRental.png' %}" height="50px" alt=""></div>
        <div class="isi">
            <div class="tentang-kami">
                <h3>Tentang Kami</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia, corrupti. Praesentium velit laudantium ab fuga numquam exercitationem quis, distinctio voluptatibus eaque accusantium debitis officiis. Ab voluptates commodi iure pariatur aut!x</p>
            </div>
            <div class="kontak-lokasi">
                <div class="lokasi">
                    <h5>Lokasi</h5>
                    <p>Kampus UI Depok, Pondok Cina, Kecamatan Beji, Kota Depok, Jawa Barat 16424<br>Jam buka:<br>Buka 08.00 Tutup pukul 17.00</p>
                </div>
                <div class="kontak">
                    <span><a href="mailto:"><b>rentalalex@info.com</b></a></span>
                    <div class="sosmed">
                        <a href=""><img src="{% static 'img/linkedin.png' %}" height="24px" alt=""></a>
                        <a href=""><img src="{% static 'img/17216.png' %}" height="24px" alt=""></a>
                        <a href=""><img src="{% static 'img/whatsap.png' %}" height="24px" alt=""></a>
                        <a href=""><img src="{% static 'img/facebook.png' %}" height="24px" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% block js %}

{% endblock js %}
</body>
</html>