mobil/urls.py
from django.urls import path
from . import views

app_name = 'mobil'

urlpatterns = [
    path('', views.list_mobil, name='list_mobil'),
    path('getAllCarData/', views.getAllCarData, name='getAllCarData'),
    path('tambah/', views.tambah_mobil, name='tambah_mobil'),
    path('detail/<int:index>/', views.detail_mobil, name='detail_mobil'),
    path('add-fav/', views.add_fav, name='add_fav'),
]

sewaAlex/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('users.urls')),
    path('transaksi/', include('transaksi.urls')),
    path('admin/', admin.site.urls),
    path('artikel/', include('artikel.urls')),
    path('mobil/', include('mobil.urls')),
    path('ulasan/', include('ulasan.urls')),
    path('', include('social_django.urls', namespace='social')),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile_page, name='profile'),
    path('signup/', views.signup_page, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_acc, name='logout'),
    path('edit_profile/', views.edit_profile, name='edit_profile')
]

users/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from mobil.models import Car

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    tgl_lahir = models.DateField('tgl lahir', null=True, blank=True)
    nama = models.CharField('nama', max_length=100, null=True)
    no_hp = models.CharField('hp', max_length=20, null=True)
    kota = models.CharField('kota', blank=True, max_length=200, null=True)
    favorit = models.ManyToManyField(Car)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from .models import Profile

# Create your views here.
def index(request):
    home = True
    return render(request, "home.html", {'home' : home})

def profile_page(request):
    if request.user.is_authenticated:
        fav_car = request.user.profile.favorit.all()
        return render(request, "users/profile.html", {'fav_car': fav_car} )
    else:
        return render(request, "users/profile.html")

def signup_page(request):
    if request.method == 'POST':
        nama = request.POST['nama']
        no_hp = request.POST['phone']
        email = request.POST['email']
        tgl_lahir = request.POST['tgl_lahir']
        kota = request.POST['kota']
        username = request.POST['username']
        password = request.POST['password']

        if(not username or not password):
            messages.error(request, "Complete your data first")
            return render(request, 'users/signup.html')

        if User.objects.filter(username__iexact=username).exists():
            messages.error(request, "Username already exist.")
            return render(request, 'users/signup.html')
        else:
            user = User.objects.create_user(username=username, password=password, email=email)
            user.profile.tgl_lahir = tgl_lahir
            user.profile.nama = nama
            user.profile.no_hp = no_hp
            user.profile.kota = kota
            user.save()

            messages.success(request, "Successfully signed in.")

            user_auth = authenticate(request, username=username, password=password)
            login(request, user_auth)

            return redirect('/profile/')
    else:
        return render(request, 'users/signup.html')

def login_page(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        if(not username or not password):
            messages.error(request, "Complete your data first")
            return render(request, 'users/login.html')

        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.error(request, "Username or password is incorrect.")
            return render(request, 'users/login.html')
    
    else:      
        return render(request, 'users/login.html')

def logout_acc(request):
    logout(request)
    messages.success(request, "Successfully logged out.")
    return redirect('/')

def edit_profile(request):
    if request.method == 'POST':
        uname = request.POST['username']
        password = request.POST['password']
        no_hp = request.POST['phone']
        kota = request.POST['kota']
        email = request.POST['email']

        if (no_hp is not None) and (kota is not None) and (email is not None):
            user = authenticate(request, username=uname, password=password)
            user.profile.no_hp = no_hp
            user.profile.kota = kota
            user.email = email
            user.save()
        else:
            messages.error(request, "Please complete all your data first.")
            return redirect('/profile')
    
        return redirect('/profile')
    else:
        return render(request, 'users/ubah_data.html')

templates/users/login.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
	<link rel="stylesheet" href="{% static 'css/users/users_form.css' %}">
{% endblock css%}

{% block title %} Login {% endblock title%}

{% block content %}
<div class="content">
	<section class="px-5 justify-content-center">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <script>
            alert("{{ message }}")
        </script>
        {% endfor %}
    </ul>
    {% endif %}
		<h1 class="my-4 mx-auto font-weight-bold"> 
			Login untuk melakukan transaksi
		</h1>
    <div class="form-login">
      <form action="" method="post" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
            <div class="form-group">
              <label for="username">Username</label>
              <input id="username" name="username" class="form-control" type="text" placeholder="Username" required>
            </div>
            <div class="form-group">
              <label for="password">Password</label>
              <input id="password" name="password" class="form-control" type="password" placeholder="Password" required>
            </div>
            <button id="login-submit" type="submit" class="btn btn-primary">Submit</button>
            <a id="signup" class="btn btn-outline-warning" href="{% url 'users:signup' %}"> Sign Up </a>
            <hr/>
            <small class="googleSignIn">Sign In dengan cara lain :</small>
            <div class="login-google" onclick="location.href='{% url 'social:begin' 'google-oauth2' %}'" style="cursor: pointer;">
              <img src="{% static 'img/googleSigninButton.png' %}" width="200" alt=""/>
            </div>
      </form>
    </div>
	</section>
</div>
{% endblock content %}

templates/users/profile.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
	<link rel="stylesheet" href="{% static 'css/mobil/style_detail.css' %}">
{% endblock css%}

{% block title %} Profile {% endblock %}

{% block content %}
<div class="content">
	<section class="px-5 flex-container justify-content-center">
        {% if messages %}
        <ul class="messages">
              {% for message in messages %}
            <script>
                alert("{{ message }}")
            </script>
              {% endfor %}
        </ul>
        {% endif %}
    
        {% if user.is_authenticated %}
        <div class="flex-container justify-content-center">
            <h1>Halo, {{ user.username }}!</h1><br/>
            <h3>Informasi Pribadi</h3>
        </div>
        <div>
            <table class="table" style="width:30%;">
                <br/>
                <tr>
                  <td>Nama Lengkap</td>
                  <td>: {{ user.profile.nama }}</td>
                </tr>
                <tr>
                    <td>Username</td>
                    <td>: {{ user.username }}</td>
                </tr>
                <tr>
                  <td>Password</td>
                  <td>: ****** </td>
                </tr>
                <tr>
                  <td>Nomor Telepon</td>
                  <td>: {{ user.profile.no_hp }}</td>
                </tr>
                <tr>
                  <td>Email</td>
                  <td id='email-data'>: {{ user.email }}</td>
                </tr>
                <tr>
                  <td>Tanggal Lahir</td>
                  <td>: {{ user.profile.tgl_lahir }}</td>
                </tr>
                <tr>
                    <td>Kota Domisili</td>
                    <td>: {{ user.profile.kota }}</td>
                </tr>
                <!-- <tr> -->
                    <!-- <td></td> -->
                <!-- </tr> -->
              </table>
        </div>
        <div>
          <a id="ubah" class="mt-3 mb-5 btn btn-warning" href="{% url 'users:edit_profile' %}">Update Data Diri</a>
          <a id='logout-btn' class="mt-3 mb-5 btn btn-warning" href="{% url 'users:logout' %}">Logout</a>
        </div>
        {% else %}
            <h1>Login untuk melakukan transaksi.</h1>
        {% endif %}
	</section>

  {% if user.is_authenticated %}
  <section class="px-5 justify-content-center">
    <h3 class="mb-4"> Mobil Favoritmu </h3>
    <div class="bodyContent d-flex justify-content-around">
      {% for car in fav_car %}
        <div id="{{car.id}}" class="card m-3 p-3 shadow" style="width: 450px;">
          <img src="{% static 'img/mobil/car-black_3.png' %}" class="card-img-top" style="cursor:pointer" onclick="location.href='{% url 'mobil:detail_mobil' car.id %}'">
          <div class="card-body">
            <h5 class="card-title">
              <span style="width: 450px; cursor:pointer;" onclick="location.href='{% url 'mobil:detail_mobil' car.id %}'">
                {{ car.mobil }}
              </span>
              <i id="{{ car.id }}" class="fa fa-heart click-heart red"></i>
            </h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ car.harga }}</h6>
            <p class="card-text">{{ car.deskripsiSnippet }}</p>
          </div>
        </div>
      {% endfor %}
    </div>
  </section>
  {% endif %}
</div>
{% endblock %}
{% block js %}
  <script src="https://kit.fontawesome.com/aa8d881418.js" crossorigin="anonymous"></script>
  <script src="{% static 'js/profile.js' %}"></script> 
{% endblock js %}

templates/users/signup.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/users/users_form.css' %}">
{% endblock css%}
{% block title %} Login {% endblock title%}

{% block content %}
<div class="content">
	<section class="px-5 justify-content-center">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <script>
                alert("{{ message }}")
            </script>
            {% endfor %}
        </ul>
        {% endif %}
		<h1 class="mx-auto my-4 font-weight-bold"> 
			Sign up untuk melakukan transaksi
		</h1>
        <div class="form-login">
            <form action="" method="post" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                    <div class="form-group">
                        <label for="nama">Nama Lengkap: </label>
                        <input id="nama" name="nama" class="form-control" type="text" placeholder="Nama lengkap anda" required>
                    </div>
                    <div class="form-group">
                        <label for="phone">Nomor Telepon: </label>
                        <input id="phone" name="phone" class="form-control" type="tel" placeholder="No Hp yang dapat dihubungi" required>
                    </div>
                    <div class="form-group">
                        <label for="email">Email: </label>
                        <input id="email" name="email" class="form-control" type="email" placeholder="Alamat email anda" required>
                    </div>
                    <div class="form-group">
                        <label for="tgl_lahir">Tanggal Lahir: </label>
                        <input id="tgl_lahir" name="tgl_lahir" class="form-control" type="date" placeholder="Tanggal " required>
                    </div>
                    <div class="form-group">
                        <label for="kota">Kota Domisili: </label>
                        <input id="kota" name="kota" class="form-control" type="text" placeholder="Kota tinggal" required>
                    </div>
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input id="username" name="username" class="form-control" type="text" placeholder="Username" required>
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input id="password" name="password" class="form-control" type="password" placeholder="Password" required>
                    </div>
                    <button id="signup-submit" type="submit" class="btn btn-primary">Submit</button>
                    <a id="login" class="btn btn-outline-warning" href="{% url 'users:login' %}"> Login </a>
                    <hr/>
                    <small class="googleSignIn">Sign In dengan cara lain :</small>
                    <div class="login-google" onclick="location.href='{% url 'social:begin' 'google-oauth2' %}'" style="cursor: pointer;">
                        <img src="{% static 'img/googleSigninButton.png' %}" width="200" alt=""/>
                    </div>
            </form>
        </div>
	</section>
</div>
{% endblock content %}

templates/users/ubah_data.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/users/users_form.css' %}">
{% endblock css%}
{% block title %} Login {% endblock title%}

{% block content %}
<div class="content">
	<section class="px-5 justify-content-center">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <script>
                alert("{{ message }}")
            </script>
            {% endfor %}
        </ul>
        {% endif %}
		<h1 class="mx-auto mb-4 font-weight-bold"> 
			Update data diri
		</h1>
        <h4>Data yang dapat diubah hanya yang terdapat pada fom ini.</h5>
        <h5>Untuk mengubah data lain, hubungi Administrator pada kontak di bawah.</h5><br/>

        

            <form action="" method="post" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
            <table>
            <tr>
                <td><label for="phone">Nomor Telepon:</label></td>
                <td><input type="tel" id="phone" name="phone" placeholder="0878 8755 0000"required></td><br/>
            </tr>

            <tr>
                <td><label for="email">Email:</label></td>
                <td><input type="email" id="email" name="email"><br/></td>
            </tr>

            <tr>
                <td><label for="kota">Kota Domisili: </label></td>
                <td><input id="kota" name="kota" type="text" required></td><br/>
            </tr>
        </table>

        
            <br>
            <h5>Masukan username dan password anda untuk memastikan</h5>
            <h5>bahwa ini benar-benar anda.</h5>
            <br>
            <table>
            <tr>
                <td><label for="username">Username: </label></td>
                <td><input id="username" name="username" type="text" required></td><br/>
            </tr>
        
            <tr>
                <td><label for="password">Password: </label></td>
                <td><input id="password" name="password" type="password" required></td><br/>
            </tr>
        </table>
                <br/>
                <input id="update-submit" type="submit" value="Update" class="btn btn-primary">
            
        </form>
	</section>
</div>
{% endblock content %}